{{- if .Values.nginx.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "tap-php.fullname" . }}-nginx
  labels:
    {{- include "tap-php.labels" . | nindent 4 }}
  annotations:
    metric-config.external.prometheus-query.prometheus/nginx_http_requests_total: |
     ceil(max(rate(nginx_http_requests_total{job="{{ include "tap-php.fullname" . }}-nginx",namespace="{{ .Release.Namespace}}"}[30s])))
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "tap-php.fullname" . }}-nginx
  minReplicas: {{ .Values.nginx.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.nginx.autoscaling.maxReplicas }}
  {{- if .Values.nginx.autoscaling.behavior }}
  behavior:
    {{- toYaml .Values.nginx.autoscaling.behavior | nindent 4 }}
  {{- end }}
  metrics:
    - type: External
      external:
        metric:
          name: prometheus-query
          selector:
            matchLabels:
              query-name: nginx_http_requests_total
        target:
          type: Value
          value: "{{ .Values.nginx.autoscaling.value }}"
{{- end }}
