apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tap-php.fullname" . }}-env-fpm
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "tap-php.fullname" $ }}-fpm
data:
{{- range $k,$v := .Values.env.fpm }}
  {{ $k }}: {{ $v | toString | b64enc | quote }}
{{- end }}
{{- if eq .Values.mysql.source "env" -}}
{{- range $k,$v := .Values.env.mysql }}
  {{ $k }}: {{ $v | toString | b64enc | quote }}
{{- end }}
{{- end }}
{{- if eq .Values.mysql_log.source "env" -}}
{{- range $k,$v := .Values.env.mysql_log }}
  {{ $k }}: {{ $v | toString | b64enc | quote }}
{{- end }}
{{- end }}
{{- range $k,$v := .Values.env.memcached }}
  {{ $k }}: {{ $v | toString | b64enc | quote }}
{{- end }}
