{{- if .Values.env }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tap-front.fullname" . }}-env
  labels:
    {{- include "tap-front.labels" . | nindent 4 }}
data:
{{- range $k,$v := .Values.env }}
  {{ $k }}: {{ $v | toString | b64enc| quote }}
{{- end }}
{{- end }}
---
{{- if .Values.env }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tap-front.fullname" . }}-json
  labels:
    {{- include "tap-front.labels" . | nindent 4 }}
data:
  env.json: {{ .Values.env | toJson | b64enc | quote }}
{{- end }}
