apiVersion: v1
kind: Service
metadata:
  name: {{ include "tap-ton.fullname" . }}
  labels:
    {{- include "tap-ton.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tap-ton.selectorLabels" . | nindent 4 }}
    app: tap-ton
